name: Jasmine Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: npm install
    - name: Run Jasmine tests
      run: |
        npm test
        if [ $? -gt 0 ]; then
          echo "Test failed. Push rejected."
          exit 3
        fi 

