name: Jasmine Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: npm install
    - name: Run Jasmine Test
      run : npm test
    - name: Run Pre-Commit
      uses: pre-commit/action@v3

